-- ============================================================
-- CADguard Supabase Init — HACKATHON MODE (no RLS, no policies)
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Analyses table
CREATE TABLE IF NOT EXISTS public.analyses (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    file_name       TEXT NOT NULL,
    material        TEXT NOT NULL,
    risk_score      REAL NOT NULL,
    risk_label      TEXT NOT NULL,
    features        JSONB,
    violations      JSONB,
    shap_values     JSONB,
    recommendations JSONB,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Users table for backend authentication
CREATE TABLE IF NOT EXISTS public.users (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email      TEXT UNIQUE NOT NULL,
    password   TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_analyses_created_at ON public.analyses (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_email         ON public.users (email);

-- ⚠️  DISABLE RLS — hackathon mode, no security layers
ALTER TABLE public.analyses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

-- Drop any existing policies that might interfere
DROP POLICY IF EXISTS analyses_select_public ON public.analyses;

-- Seed initial admin user (bcrypt hash generated by pgcrypto)
INSERT INTO public.users (email, password)
VALUES (
    'admin@designcopilot.ai',
    crypt('admin123', gen_salt('bf'))
)
ON CONFLICT (email) DO NOTHING;
